{"uuid": "5228efee-163f-4fea-b948-c06531c914f4", "children": ["960efb87-45b3-4445-abc0-a9c05669713b", "7f4c90a8-826d-47ba-9fd1-9f95488b7609", "65ee203f-af96-4db7-95f7-67c2fdd10547", "6229226b-1827-4b80-961d-243e55bfdeb5", "a200909e-bd59-484b-820f-5e4e454fcafd", "b4307d14-43c4-4e7f-9c97-cae523d12fa5", "581ba394-c741-41ca-b8ac-0cc4b556fdff", "615121d9-310a-49e5-81a5-be7574bf8025", "7e833ef3-9b1e-4bb3-a1cd-fa3072ee2477", "0f900978-f1e0-4209-8cdd-bf103e497d12", "768487f3-a39f-4f80-a574-6b5fdbdc7b1b", "7bb34335-091c-4862-85d7-d3bcf7df5b63", "f36eb08c-fb6e-4c45-96d9-4265d05e640d", "193dbcf0-adb2-422a-89b1-273b79da1c33", "2d58bcd0-24e9-4ef4-9c70-c81848f03893", "d05d693f-67b3-4298-b5aa-458fb27039ee", "e4806ccf-a339-47cc-ad1a-6ee5742dc327", "45595ebd-ecb8-4f7d-9e72-292522700728", "e6f9a96f-6c8b-43e9-80ce-de07681cef18", "ee56adce-a0a7-4790-82a8-1031c1163bb8", "ec0d21da-4098-4ab4-8c3e-7194e3dc8afb", "9dce25de-e645-4645-8d21-99eb647b0be7", "44e544d7-4d65-4da9-80e4-2c963a77bb21", "a0a83683-594a-4461-80f9-1d26a92c6a06", "c9d8247a-aa77-480f-8ef7-72079456ff66", "c284f9be-c383-4b11-904b-e886a52e497a", "aa830c71-1060-49f5-94fd-9afb7c586d12"], "befores": [{"name": "__init__", "status": "failed", "statusDetails": {"message": "AssertionError: None\nassert 'http://10.250.112.166:9000/#/dashboard' in 'http://10.250.112.166:9000/#/'\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\售后自动化\\UIPOMTest\\project\\DRP\\test_case\\conftest.py\", line 22, in __init__\n    user.assert_url(\"{}/dashboard\".format(ini.url))\n  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\assert_ui.py\", line 189, in assert_url\n    assert word in att, logging.warning(\"断言失败：URL为预期不一致 | URL: {}\".format(att))\n"}, "steps": [{"name": "值为True值断言", "status": "failed", "statusDetails": {"message": "AssertionError: None\nassert 'http://10.250.112.166:9000/#/dashboard' in 'http://10.250.112.166:9000/#/'\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\assert_ui.py\", line 189, in assert_url\n    assert word in att, logging.warning(\"断言失败：URL为预期不一致 | URL: {}\".format(att))\n"}, "parameters": [{"name": "word", "value": "'http://10.250.112.166:9000/#/dashboard'"}], "start": 1658658685465, "stop": 1658658686063}], "start": 1658658637877, "stop": 1658658686075}], "start": 1658658637877, "stop": 1658658695809}