{"uuid": "87a666c0-fb1a-4229-b6e0-01f33047479a", "children": ["e876006b-bfdd-4e3d-bc46-e52891982025", "6c7816d0-3931-4b96-b05c-bbbffd6efa7c", "04a576e0-24b4-4f1b-bd0a-ebdf06db783f", "c0088eb6-b8d8-4fd0-8d97-23619f2def4e", "5b8ab0e9-9408-447e-b507-17164066828a", "fa3aa798-d4e9-4e92-b09b-d9bdd7bc031f", "4cb25603-0316-4b35-8a15-7c2c3fa72ab9", "338f7b55-fbba-4282-b930-f6efbe76219e", "57332482-52db-46c0-8a80-72d7f860ce55"], "befores": [{"name": "module_setup_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=99.0.4844.84)\nStacktrace:\n#0 0x55c7ecb5c7d3 <unknown>\n#1 0x55c7ec8b851f <unknown>\n#2 0x55c7ec8efd65 <unknown>\n#3 0x55c7ec8e3a19 <unknown>\n#4 0x55c7ec90c6b2 <unknown>\n#5 0x55c7ec8e32c3 <unknown>\n#6 0x55c7ec90c7be <unknown>\n#7 0x55c7ec91fa0c <unknown>\n#8 0x55c7ec90c5a3 <unknown>\n#9 0x55c7ec8e1ddc <unknown>\n#10 0x55c7ec8e2de5 <unknown>\n#11 0x55c7ecb8d49d <unknown>\n#12 0x55c7ecba660c <unknown>\n#13 0x55c7ecb8f205 <unknown>\n#14 0x55c7ecba6ee5 <unknown>\n#15 0x55c7ecb83070 <unknown>\n#16 0x55c7ecbc2488 <unknown>\n#17 0x55c7ecbc260c <unknown>\n#18 0x55c7ecbdbc6d <unknown>\n#19 0x7fc076d29609 <unknown>\n\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\app\\Python10\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\售后自动化\\UIPOMTest\\project\\CRM\\test_case\\RC_BasicDataMgt_SymptomGroupMgt.py\", line 29, in module_setup_fixture\n    user.GoTo_Symp()  # 进入现象组页面\n  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\project\\CRM\\page_object\\RC_BasicDataMgt_SymptomGroupMgt.py\", line 22, in GoTo_Symp\n    self.is_click(user['Symptom Group Mgt'])\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\basics.py\", line 205, in is_click\n    self.find_element(locator).click()\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 81, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 710, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "进入现象组页面", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=99.0.4844.84)\nStacktrace:\n#0 0x55c7ecb5c7d3 <unknown>\n#1 0x55c7ec8b851f <unknown>\n#2 0x55c7ec8efd65 <unknown>\n#3 0x55c7ec8e3a19 <unknown>\n#4 0x55c7ec90c6b2 <unknown>\n#5 0x55c7ec8e32c3 <unknown>\n#6 0x55c7ec90c7be <unknown>\n#7 0x55c7ec91fa0c <unknown>\n#8 0x55c7ec90c5a3 <unknown>\n#9 0x55c7ec8e1ddc <unknown>\n#10 0x55c7ec8e2de5 <unknown>\n#11 0x55c7ecb8d49d <unknown>\n#12 0x55c7ecba660c <unknown>\n#13 0x55c7ecb8f205 <unknown>\n#14 0x55c7ecba6ee5 <unknown>\n#15 0x55c7ecb83070 <unknown>\n#16 0x55c7ecbc2488 <unknown>\n#17 0x55c7ecbc260c <unknown>\n#18 0x55c7ecbdbc6d <unknown>\n#19 0x7fc076d29609 <unknown>\n\n", "trace": "  File \"D:\\app\\Python10\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\售后自动化\\UIPOMTest\\project\\CRM\\page_object\\RC_BasicDataMgt_SymptomGroupMgt.py\", line 22, in GoTo_Symp\n    self.is_click(user['Symptom Group Mgt'])\n  File \"D:\\售后自动化\\UIPOMTest\\public\\base\\basics.py\", line 205, in is_click\n    self.find_element(locator).click()\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 81, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 710, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\app\\Python10\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1661437157567, "stop": 1661437170662}], "start": 1661437157564, "stop": 1661437170666}], "start": 1661437157564, "stop": 1661437171633}